Repository CheckIt-v3/frontend, pull requests merged in 2023-11, with the labels that each got.

#83 [Feat/#81] 검색 페이지 → 책 한권 조회 API 로 변경
  src/components/search/PopularBook.tsx
  src/components/search/RecentBooks.tsx
  src/components/search/swiper/PopularSwipe.tsx
  src/components/search/swiper/RecentSwipe.tsx
  src/components/search/swiper/ViewedSwipe.tsx
Labels: 기능구현

#84 [Feat/#80] 통계 페이지 데이터 없는 날짜도 x축 표시되게 수정
  package.json
  src/components/statistics/BarChart.tsx
  src/components/statistics/LineChart.tsx
  yarn.lock
Labels: 환경설정, 기능구현

#88 [Fix/#82] 내서재 상세모달창, 리뷰모달창 리프레쉬
  src/components/shelf/DetailModal.tsx
  src/components/shelf/ReviewModal.tsx
  src/components/shelf/Writing.tsx
Labels: 오류수정

#89 [Feat/#62] 책 쌓아보기 컴포넌트 API 연동
  .gitignore
  global.d.ts
  src/components/statistics/BookModal.tsx
  src/components/statistics/Stack.tsx
  tsconfig.json
  vite-env.d.ts
Labels: 기능구현

#90 [Feat/#87] 프론트엔드 메인페이지, 검색페이지 로직 및 UI 수정
  package.json
  src/components/Header/MainHeader.tsx
  src/components/Header/MyHeader.tsx
  src/components/main/MainSlider.tsx
  src/components/main/PopularBook.tsx
  src/components/main/RecentBook.tsx
  src/components/main/ReverseSlider.tsx
  src/components/search/swiper/PopularSwipe.tsx
  src/components/search/swiper/RecentSwipe.tsx
  src/components/search/swiper/ViewedSwipe.tsx
  src/components/shelf/DetailModal.tsx
  src/components/shelf/ReviewModal.tsx
  src/components/shelf/Writing.tsx
  src/pages/LoginPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignUpPage.tsx
  yarn.lock
Labels: 기능구현

#91 [Feat/#86] 별점 연동
  src/components/shelf/ReviewModal.tsx
  src/components/shelf/StartRate.tsx
  src/components/shelf/Writing.tsx
Labels: 기능구현

#92 [Design] 문의하기 퍼블리싱 + 기능구현
  package.json
  src/assets/images/send.png
  src/components/search/AdminChatModal.tsx
  src/components/search/Ask.tsx
  src/components/search/ChatModal.tsx
  src/pages/SearchPage.tsx
  yarn.lock
Labels: 기능구현, 퍼블리싱
