Repository CheckIt-v3/frontend, pull requests merged in 2023-09, with the labels that each got.

#43 [feat/#42] 전반적인 페이지 라우팅 수정
  src/components/NavigationBar.tsx
  src/pages/BookDetail.tsx
  src/pages/BookSearch.tsx
  src/pages/EndShelf.tsx
  src/pages/ReadingShelf.tsx
  src/pages/SearchDetail.tsx
  src/scss/Search.scss
Labels: 기능구현, 퍼블리싱

#45 [chore/#44] CRA + NPM → VITE + YARN 마이그레이션 진행 완료
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  public/vite.svg
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 환경설정

#50 [design/#47] 메인페이지 퍼블리싱 진행
  package.json
  public/img/book1.png
  public/img/book10.png
  public/img/book11.png
  public/img/book12.png
  public/img/book2.png
  public/img/book3.png
  public/img/book4.png
  public/img/book5.png
  public/img/book6.png
  public/img/book7.png
  public/img/book8.png
  public/img/book9.png
  public/logo.png
  src/components/main/Header.tsx
  src/components/main/MainFirst.tsx
  src/components/main/MainSecond.tsx
  src/components/main/MainSlider.tsx
  src/components/main/MainThird.tsx
  src/components/main/PopularBook.tsx
  src/components/main/ResentBook.tsx
  src/components/main/ReverseSlider.tsx
  src/components/main/StartNavigator.tsx
  src/fonts/bmfont.ttf
  src/index.css
  src/pages/MainPage.tsx
  src/scss/Slider.scss
  tailwind.config.js
  yarn.lock
Labels: 퍼블리싱

#51 [Design/#49] 책 검색 페이지 퍼블리싱
  .prettierrc
  .prettierrc.js
  package.json
  src/App.tsx
  src/components/search/Ask.tsx
  src/components/search/SearchBar.tsx
  src/components/search/swiper/Swipe.tsx
  src/components/search/swiper/styles.css
  src/pages/SearchPage.tsx
  yarn.lock
Labels: 퍼블리싱

#55 [Design/#52] 로그인 + 회원가입 페이지 (+검색 페이지 일부분) 퍼블리싱
  public/img/Bar1.png
  public/img/Bar2.png
  public/img/Bar3.png
  src/App.tsx
  src/components/Btn/SignUpBtn.tsx
  src/components/Header/Header.tsx
  src/components/Header/LoginHeader.tsx
  src/components/Header/MyHeader.tsx
  src/components/Input/LoginInput.tsx
  src/components/main/Header.tsx
  src/components/search/Ask.tsx
  src/components/search/SearchBar.tsx
  src/components/search/swiper/Swipe.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignUpPage.tsx
  yarn.lock
Labels: 기능구현, 퍼블리싱

#57 [Design/#54] 통계 차트 페이지 퍼블리싱
  src/App.tsx
  src/components/statistics/BarChart.tsx
  src/components/statistics/Header.tsx
  src/components/statistics/LineChart.tsx
  src/components/statistics/StatisticsHeader.tsx
  src/components/statistics/StatisticsToolbar.tsx
  src/components/statistics/Toolbar.tsx
  src/pages/EndShelf.tsx
  src/pages/Statistics.tsx
  yarn.lock
Labels: 기능구현, 퍼블리싱

#58 [Design/#56] 독서 통계 선택 페이지 퍼블리싱
  public/img/books.png
  public/img/statistics.png
  src/App.tsx
  src/components/Header/MyHeader.tsx
  src/pages/ChoosePage.tsx
Labels: 퍼블리싱
