Repository CheckIt-v3/frontend, pull requests merged in 2023-10, with the labels that each got.

#60 [Design/#48] 내 서재 페이지 퍼블리싱
  .prettierrc
  package.json
  src/App.tsx
  src/assets/fonts/bmfont.ttf
  src/assets/images/1.png
  src/assets/images/10.png
  src/assets/images/11.png
  src/assets/images/12.png
  src/assets/images/13.png
  src/assets/images/2.png
  src/assets/images/3.png
  src/assets/images/4.png
  src/assets/images/5.png
  src/assets/images/6.png
  src/assets/images/7.png
  src/assets/images/8.png
  src/assets/images/9.png
  src/assets/images/nextBtn.svg
  src/assets/images/prevBtn.svg
  src/components/main/Header.tsx
  src/components/shelf/BookModal.tsx
  src/components/shelf/Books.tsx
  src/components/shelf/ChangeShelf.tsx
  src/components/shelf/DetailModal.tsx
  src/components/shelf/Header.tsx
  src/components/shelf/ReviewModal.tsx
  src/components/shelf/Shelf.tsx
  src/index.css
  src/pages/BookShelfPage.tsx
  src/scss/MyShelf.scss
  src/scss/Shelf.scss
  tailwind.config.js
  yarn.lock
Labels: 기능구현, 퍼블리싱

#61 [design/#53] 책 쌓아보기 페이지 퍼블리싱
  .gitignore
  package.json
  public/book.fbx
  src/App.tsx
  src/components/statistics/Stack.tsx
  src/pages/BookStackPage.tsx
  yarn.lock
Labels: 퍼블리싱

#64 [Feat/#59] 로그인 + 회원가입 페이지 api 연동
  src/api/config.ts
  src/components/Btn/SignUpBtn.tsx
  src/components/main/StartNavigator.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  vite.config.ts
  yarn.lock
Labels: 기능구현

#68 chore: checkit v1 파일 리팩토링 및 제거
  src/components/Header.tsx
  src/components/NavigationBar.tsx
  src/components/main/Header.tsx
  src/components/search/SearchDetail.tsx
  src/components/search/StatBtn.tsx
  src/components/search/StatusButton.tsx
  src/components/shelf/BookDetail.tsx
  src/components/shelf/BookModal.tsx
  src/components/shelf/DetailPercent.tsx
  src/components/shelf/Divider.tsx
  src/components/shelf/PagesModal.tsx
  src/components/statistics/BookStack.tsx
  src/pages/BookSearch.tsx
  src/pages/EndShelf.tsx
  src/pages/MainPage.tsx
  src/pages/ReadingShelf.tsx
  src/pages/WishShelf.tsx
Labels: 환경설정

#70 [feat/#65] 최근 출시작, 인기 책 API 연동
  src/api/config.ts
  src/components/search/PopularBook.tsx
  src/components/search/ResentBooks.tsx
  src/components/search/ViewedBooks.tsx
  src/components/search/swiper/ResentSwipe.tsx
  src/pages/SearchPage.tsx
Labels: 기능구현

#71 Feat/#63
  .gitignore
  src/components/shelf/Books.tsx
  src/components/shelf/ChangeShelf.tsx
  src/components/shelf/DetailModal.tsx
  src/components/shelf/ReviewModal.tsx
  src/components/shelf/Shelf.tsx
  src/components/shelf/Writing.tsx
  src/pages/BookShelfPage.tsx
  src/scss/BookReview.scss
  yarn.lock
Labels: 기능구현, 퍼블리싱

#72 [Feat/#66] 로그아웃 + 통계 - 모아보기 페이지 api 연동 + 시작하기 버튼 navigate + 헤더 퍼블리싱 수정
  src/components/Header/MainHeader.tsx
  src/components/Header/MyHeader.tsx
  src/components/Header/ShelfHeader.tsx
  src/components/main/StartNavigator.tsx
  src/components/statistics/BarChart.tsx
  src/components/statistics/LineChart.tsx
  src/pages/MainPage.tsx
  src/pages/Statistics.tsx
Labels: 기능구현, 퍼블리싱

#75 [Feat/#69] 검색 페이지 API 연동하기
  src/components/search/PopularBook.tsx
  src/components/search/RecentBooks.tsx
  src/components/search/ViewedBooks.tsx
  src/components/search/swiper/PopularSwipe.tsx
  src/components/search/swiper/RecentSwipe.tsx
  src/components/search/swiper/ViewedSwipe.tsx
  src/pages/SearchPage.tsx
Labels: 기능구현
